<?php
// Delete options before ver.1.5
delete_option('wp_sh_highlight_home');
delete_option('wp_sh_highlight_posts');
delete_option('wp_sh_highlight_categories');
delete_option('wp_sh_highlight_archives');
delete_option('wp_sh_highlight_search');
delete_option('wp_sh_highlight_comment');
delete_option('wp_sh_highlight_widgets');
delete_option('wp_sh_highlight_others');
delete_option('wp_sh_theme');
delete_option('wp_sh_auto_links');
delete_option('wp_sh_addl_style_enable');
delete_option('wp_sh_collapse');
delete_option('wp_sh_padding_line');
delete_option('wp_sh_smart_tabs');
delete_option('wp_sh_tab_size');
delete_option('wp_sh_toolbar');
delete_option('wp_sh_wrap');
delete_option('wp_sh_legacy');
delete_option('wp_sh_css');
delete_option('wp_sh_insert');
delete_option('wp_sh_button');
delete_option('wp_sh_codebox');
delete_option('wp_sh_button_window_size');
delete_option('wp_sh_button_row');
delete_option('wp_sh_comment_hl_bt_enable');
delete_option('wp_sh_comment_hl_description_before_enable');
delete_option('wp_sh_comment_hl_stylesheet_enable');
?>